name: Build adpcm-xq

on:
  push:
    branches:
      - master

jobs:
  build:
    defaults:
      run:
        shell: msys2 {0}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: windows-11-arm
            ARTIFACT_PREFIX: winarm64
            MSYS2_SYS: CLANGARM64
          - os: windows-latest
            ARTIFACT_PREFIX: win64
            MSYS2_SYS: UCRT64
    steps:
      - name: 'Configure git: core.autocrlf, core.eol'
        shell: pwsh
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v5
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.MSYS2_SYS}}
          update: true
          pacboy: >-
            cmake:p
            ninja:p
            toolchain:p
      - name: Build
        run: |
          cmake -B build -S .
          cmake --build build
      - name: Copy files
        run: |
          mkdir upload
          cp license.txt upload
          cp build/*.exe upload
          strip upload/*.exe
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: adpcm-xq-git-${{matrix.ARTIFACT_PREFIX}}-${{github.sha}}
          path: upload
          if-no-files-found: error
